/**
 * Battery
 *
 * The uCIFI battery object provides attributes to monitor battery level and
 * activity.
 *
 * @see https://github.com/OpenMobileAlliance/lwm2m-registry/raw/prod/3411.xml
 *
 * ID: 3411
 * LWM2MVersion: 1.0
 * ObjectVersion: 1.1
 * MultipleInstances: true
 * Mandatory: false
 */
export type Battery_3411 = Readonly<
	Array<{
		'1': Batterylevel_1
		'2'?: Batterycapacity_2
		'3'?: Batteryvoltage_3
		'4'?: Typeofbattery_4
		'5'?: Lowbatterythreshold_5
		'6'?: Batteryleveltoolow_6
		'7'?: Batteryshutdown_7
		'8'?: Numberofcycles_8
		'9'?: Supplyloss_9
		'10'?: Supplylosscounter_10
		'12'?: Supplylossreason_12
		'5518'?: Timestamp_5518
		'6042'?: MeasurementQualityIndicator_6042
		'6049'?: MeasurementQualityLevel_6049
		'6050'?: FractionalTimestamp_6050
	}>
>
/**
 * Battery level
 *
 * Level of charge of the battery in % of total possible charge.
 *
 * ID: 1
 * MultipleInstances: false
 * Mandatory: true
 * Units: /100
 */
type Batterylevel_1 = number
/**
 * Battery capacity
 *
 * Nominal capacity of the battery in Ampere hour.
 *
 * ID: 2
 * MultipleInstances: false
 * Mandatory: false
 * Units: Ah
 */
type Batterycapacity_2 = number
/**
 * Battery voltage
 *
 * Level of charge of the battery in Volts.
 *
 * ID: 3
 * MultipleInstances: false
 * Mandatory: false
 * Units: V
 */
type Batteryvoltage_3 = number
/**
 * Type of battery
 *
 * Describes the type of battery (e.g. Li-Ion rechargeable).
 *
 * ID: 4
 * MultipleInstances: false
 * Mandatory: false
 */
type Typeofbattery_4 = string
/**
 * Low battery threshold
 *
 * Threshold below which an event is generated by the device.
 *
 * ID: 5
 * MultipleInstances: false
 * Mandatory: false
 * Units: /100
 */
type Lowbatterythreshold_5 = number
/**
 * Battery level too low
 *
 * Set to True if battery level is below or equal the low battery threshold. Set
 * to False otherwise.
 *
 * ID: 6
 * MultipleInstances: false
 * Mandatory: false
 */
type Batteryleveltoolow_6 = boolean
/**
 * Battery shutdown
 *
 * Indicates that the device has shut down due to battery discharge. Can be
 * reset by central application.
 *
 * ID: 7
 * MultipleInstances: false
 * Mandatory: false
 */
type Batteryshutdown_7 = boolean
/**
 * Number of cycles
 *
 * Number of times the battery has discharged and recharged.
 *
 * ID: 8
 * MultipleInstances: false
 * Mandatory: false
 */
type Numberofcycles_8 = number
/**
 * Supply loss
 *
 * Applies for battery devices that are also connected to mains supply. Set to
 * True when mains power is lost. Set to False when mains power is back.
 *
 * ID: 9
 * MultipleInstances: false
 * Mandatory: false
 */
type Supplyloss_9 = boolean
/**
 * Supply loss counter
 *
 * Number of supply losses since last reset.
 *
 * ID: 10
 * MultipleInstances: false
 * Mandatory: false
 */
type Supplylosscounter_10 = number
/**
 * Supply loss reason
 *
 * Reason identified by the device why the device has lost mains supply (e.g.
 * lightning if the device measured a high voltage, accident if the device
 * identified a move with an accelerometer).
 *
 * ID: 12
 * MultipleInstances: false
 * Mandatory: false
 */
type Supplylossreason_12 = string
/**
 * Timestamp
 *
 * The timestamp of when the measurement was performed.
 *
 * ID: 5518
 * MultipleInstances: false
 * Mandatory: false
 */
type Timestamp_5518 = number
/**
 * Measurement Quality Indicator
 *
 * Measurement quality indicator reported by a smart sensor. 0: UNCHECKED No
 * quality checks were done because they do not exist or can not be applied. 1:
 * REJECTED WITH CERTAINTY The measured value is invalid. 2: REJECTED WITH
 * PROBABILITY The measured value is likely invalid. 3: ACCEPTED BUT SUSPICIOUS
 * The measured value is likely OK. 4: ACCEPTED The measured value is OK. 5-15:
 * Reserved for future extensions. 16-23: Vendor specific measurement quality.
 *
 * ID: 6042
 * MultipleInstances: false
 * Mandatory: false
 */
type MeasurementQualityIndicator_6042 = number
/**
 * Measurement Quality Level
 *
 * Measurement quality level reported by a smart sensor. Quality level 100 means
 * that the measurement has fully passed quality check algorithms. Smaller
 * quality levels mean that quality has decreased and the measurement has only
 * partially passed quality check algorithms. The smaller the quality level, the
 * more caution should be used by the application when using the measurement.
 * When the quality level is 0 it means that the measurement should certainly be
 * rejected.
 *
 * ID: 6049
 * MultipleInstances: false
 * Mandatory: false
 */
type MeasurementQualityLevel_6049 = number
/**
 * Fractional Timestamp
 *
 * Fractional part of the timestamp when sub-second precision is used (e.g.,
 * 0.23 for 230 ms).
 *
 * ID: 6050
 * MultipleInstances: false
 * Mandatory: false
 * Units: s
 */
type FractionalTimestamp_6050 = number
/**
 * The objectURN for Battery
 * Used in the JSON schema for the LwM2M document definition as a key.
 */
export const objectURN = '3411:1.1'
